-- Creación de la BBDD de Eventos Relevantes para el tratamiento de las bolsas BMW y BIVA
/*
CREATE TABLE P_BOLSAS_EVENTOS_RELEVANTES (
    FECHA      DATE,
    N          NUMBER ,
    CLAVE      VARCHAR2(15),
    SECCION    VARCHAR2(80),
    ASUNTO     VARCHAR2(500),
    URL        VARCHAR2(350),
    ARCHIVO    VARCHAR2(250),
    ORIGEN     VARCHAR2(6),
    T          VARCHAR2(2),
    FILTRO     VARCHAR2(10),
    FPROCESO   DATE,
    NOTA       VARCHAR2(15)
);
CREATE UNIQUE INDEX idx_P_BOLSAS_EVENTOS_RELEVANTES
ON P_BOLSAS_EVENTOS_RELEVANTES(FECHA, N, CLAVE, SECCION, ASUNTO, URL, ARCHIVO, ORIGEN, T, FILTRO);

CREATE INDEX idx_P_BOLSAS_EVENTOS_RELEVANTES_T
ON P_BOLSAS_EVENTOS_RELEVANTES(T);

CREATE INDEX idx_P_BOLSAS_EVENTOS_RELEVANTES_FECHA
ON P_BOLSAS_EVENTOS_RELEVANTES(FECHA);

CREATE INDEX idx_P_BOLSAS_EVENTOS_RELEVANTES_FECHA_T
ON P_BOLSAS_EVENTOS_RELEVANTES(FECHA, T);

*/

-- Seleccionar la Tabla Producción
SELECT * FROM P_BOLSAS_EVENTOS_RELEVANTES;
SELECT COUNT(N) as TOTAL FROM P_BOLSAS_EVENTOS_RELEVANTES;

-- Seleccionar la carga Copia Seguridad
SELECT * FROM P_BOLSAS_EVENTOS_RELEVANTES_20250602;
SELECT COUNT(N) as TOTAL FROM P_BOLSAS_EVENTOS_RELEVANTES_20250602;

-- Seleccionar la carga Histórica
SELECT * FROM P_BOLSAS_EVENTOS_RELEVANTES WHERE NOTA = 'CARGA_HISTORICO';
SELECT COUNT(N) as TOTAL FROM P_BOLSAS_EVENTOS_RELEVANTES WHERE NOTA = 'CARGA_HISTORICO';

-- Seleccionar un carga Diaria
SELECT * FROM P_BOLSAS_EVENTOS_RELEVANTES WHERE NOTA = 'CARGA_DIARIA' AND TRUNC(FPROCESO) = TO_DATE('2025-06-10', 'YYYY-MM-DD');

-- Borrar una carga Diaria
-- DELETE FROM P_BOLSAS_EVENTOS_RELEVANTES WHERE NOTA = 'CARGA_DIARIA' AND TRUNC(FPROCESO) = TO_DATE('2025-06-10', 'YYYY-MM-DD');
-- COMMIT;